-- MasterCodes INSERT
DELETE FROM master_code;
INSERT INTO master_code (class, code, label, value, created_at)
VALUES
  ('specialty', 1,  'もやす',     'burn',         datetime('now')),
  ('specialty', 2,  'さいばい',   'cultivation',  datetime('now')),
  ('specialty', 3,  'うるおす',   'moisturize',   datetime('now')),
  ('specialty', 4,  'きをきる',   'cut',          datetime('now')),
  ('specialty', 5,  'けんちく',   'architecture', datetime('now')),
  ('specialty', 6,  'じならし',   'bulldoze',     datetime('now')),
  ('specialty', 7,  'さがしもの', 'search',       datetime('now')),
  ('specialty', 8,  'そらをとぶ', 'fly',          datetime('now')),
  ('specialty', 9,  'テレポート', 'teleport',     datetime('now')),
  ('specialty', 10, 'リサイクル', 'recycle',      datetime('now')),
  ('specialty', 11, 'しわける',   'classify',     datetime('now')),
  ('specialty', 12, 'はつでん',   'electricity',  datetime('now')),
  ('specialty', 13, 'つぶす',     'crush',        datetime('now')),
  ('specialty', 14, 'ちらかす',   'scatter',      datetime('now')),
  ('specialty', 15, 'とりひき',   'transaction',  datetime('now')),
  ('specialty', 16, 'もりあげる', 'enliven',      datetime('now')),
  ('specialty', 17, 'あくび',     'yawn',         datetime('now')),
  ('specialty', 18, 'ゆめしま',   'dreamisland',  datetime('now')),
  ('specialty', 19, 'ミツあつめ', 'honeygather',  datetime('now')),
  ('specialty', 20, 'かんてい',   'appraisal',    datetime('now')),
  ('specialty', 21, 'はっこう',   'illuminate',   datetime('now')),
  ('specialty', 22, 'ペイント',   'paint',        datetime('now')),
  ('specialty', 23, 'くいしんぼ', 'gluttony',     datetime('now')),
  ('specialty', 24, 'しゅうのう', 'storage',      datetime('now')),
  ('specialty', 25, 'コレクター', 'collector',    datetime('now')),
  ('specialty', 26, 'パーティー', 'party',        datetime('now')),
  ('specialty', 27, 'DJ',        'dj',           datetime('now')),
  ('specialty', 28, 'しょくにん', 'craftsman',    datetime('now')),
  ('specialty', 29, 'ばくはつ',   'bomb',         datetime('now')),
  ('specialty', 30, 'レアもの',   'rare',         datetime('now')),
  ('environment', 1, 'あたたかい',    'warm',        datetime('now')),
  ('environment', 2, 'すずしい',      'cool',        datetime('now')),
  ('environment', 3, 'うるおっている', 'moisturized', datetime('now')),
  ('environment', 4, '乾そうしている', 'dry',         datetime('now')),
  ('environment', 5, 'あかるい',      'bright',      datetime('now')),
  ('environment', 6, 'くらい',        'dark',        datetime('now')),
  ('favorite', 1, 'あまい',   'sweet',      datetime('now')),
  ('favorite', 2, 'からい',   'spicy',      datetime('now')),
  ('favorite', 3, 'しぶい',   'bitterness', datetime('now')),
  ('favorite', 4, 'すっぱい', 'sour',       datetime('now')),
  ('favorite', 5, 'にがい',   'bitter',     datetime('now'));